# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - run: echo $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          path: main
      - run: ls -al
      - run: bash ./build.sh
        working-directory: ./main
      - uses: actions/checkout@v2
        with:
         ref: gh-pages
         path: gh-pages
         fetch-depth: 0
      - run: cp ./main/LIST.txt ./gh-pages/
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
#          git add LIST.txt
#          git commit -m "update"
        working-directory: ./gh-pages
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
